CREATE DATABASE IF NOT EXISTS game_showcase CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE game_showcase;

CREATE TABLE IF NOT EXISTS games (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  cover_image VARCHAR(500) NOT NULL,
  cloud_link VARCHAR(500) NOT NULL,
  genre VARCHAR(80) DEFAULT '',
  platform VARCHAR(80) DEFAULT '',
  summary TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
